version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: listen
    versions:
    - 3.4.1
    - 3.5.0
  - dependency-name: bootsnap
    versions:
    - 1.6.0
    - 1.7.0
    - 1.7.1
    - 1.7.2
    - 1.7.3
  - dependency-name: nokogiri
    versions:
    - 1.11.1
    - 1.11.2
  - dependency-name: rails
    versions:
    - 6.1.1
    - 6.1.2
    - 6.1.2.1
    - 6.1.3
  - dependency-name: solargraph
    versions:
    - 0.40.2
    - 0.40.3
  - dependency-name: capybara
    versions:
    - 3.35.1
  - dependency-name: browser
    versions:
    - 5.3.0
  - dependency-name: webdrivers
    versions:
    - 4.5.0
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: "@types/jest"
    versions:
    - 26.0.20
    - 26.0.21
    - 26.0.22
  - dependency-name: "@udecode/slate-plugins"
    versions:
    - 0.72.10
    - 0.72.11
    - 0.72.7
    - 0.72.8
    - 0.72.9
    - 0.73.0
    - 0.74.1
    - 0.74.3
    - 0.74.4
    - 0.75.1
  - dependency-name: "@fontsource/cormorant-sc"
    versions:
    - 4.1.0
    - 4.2.0
    - 4.2.1
    - 4.2.2
  - dependency-name: "@fontsource/inter"
    versions:
    - 4.1.0
    - 4.1.1
    - 4.2.0
    - 4.2.1
  - dependency-name: "@rails/ujs"
    versions:
    - 6.1.1
    - 6.1.2
  - dependency-name: "@rails/activestorage"
    versions:
    - 6.1.1
    - 6.1.2
  - dependency-name: "@testing-library/react"
    versions:
    - 11.2.3
    - 11.2.5
  - dependency-name: "@styled-icons/material"
    versions:
    - 10.26.0
